### PR TITLE
comments change color on hover

### PR DESCRIPTION
**Pull request by eshrh**
i love this theme and wanted to contribute! I left everything the same, but I made one small tweak - comments change color when you hover over them - i had originally made the tweak for just myself, but then I had the idea of sending a PR to the main repository so that everyone can use it. The color changes to `rgb(116, 246, 207)` over 1.5s transition duration. If there's another color that the comments could be changed to, please tell me and i'll gladly change it. I thought that this color fit in well with the blue style of the theme.

I also took the liberty of naming each of the colors in hex with comments in `colors.less` so that anyone who wants the colors real quick has easy access to them. I would also think of adding the hex values to the readme to make it ever easier, but i'll leave that decision up to y'all :D.

Thanks - eshanmind :p

### CODE REVIEW

**Comment by pathtrk** [comment]
@eshanmind Thanks for the pull request! Sorry but I've been so busy for the moment that I couldn't check your code yet. But I'll definitely look into it and perhaps your tweaks will help the theme's readability. I'm going to get back soon.

**Comment by eshrh** [comment]
can i get an update?

**Comment by pathtrk** [comment]
@eshanmind Really sorry for replying late. It seems some people don't want to have hover on their editors, So I'm going to merge your branch to "hover" branch. Thanks for the great contribution.

**Comment by eshrh** [comment]
I think you accidentally closed it instead of merging it!

**Comment by pathtrk** [comment]
@eshanmind Thanks for letting me know! I merged.

**Pull request merged**
